name = "hsk4-review"
compatibility_date = "2025-01-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "hsk4"
database_id = "f9513e61-36be-491f-9e0e-70ebf9686795"
migrations_dir = "migrations"
